# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outfitpicker < Formula
  desc "Interactive CLI to pick outfits from category folders"
  homepage "https://github.com/dh85/outfitpicker"
  version "2.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dh85/outfitpicker/releases/download/v2.0.0/outfitpicker_Darwin_x86_64.tar.gz"
      sha256 "c3ed0738cc4a9e2c569aad03e54fc2b565b8325a110805960736e83275b3f551"

      def install
        bin.install "outfitpicker"
        bin.install "outfitpicker-admin"
      end
    end
    on_arm do
      url "https://github.com/dh85/outfitpicker/releases/download/v2.0.0/outfitpicker_Darwin_arm64.tar.gz"
      sha256 "39fec997b4b43ee8e46dab8589b141cedf4c007cc892692e628db4cc33aac46f"

      def install
        bin.install "outfitpicker"
        bin.install "outfitpicker-admin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dh85/outfitpicker/releases/download/v2.0.0/outfitpicker_Linux_x86_64.tar.gz"
        sha256 "ac73387567ee29bdc0b98ee056f68f2766ced903d0d63ec6516f4efec132e8d8"

        def install
          bin.install "outfitpicker"
          bin.install "outfitpicker-admin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dh85/outfitpicker/releases/download/v2.0.0/outfitpicker_Linux_arm64.tar.gz"
        sha256 "8ac14ab1583eb9a5f99b55f673691799f4dfb1209c4fbc67bf1ac6c03b549dfa"

        def install
          bin.install "outfitpicker"
          bin.install "outfitpicker-admin"
        end
      end
    end
  end

  test do
    system "#{bin}/outfitpicker", "--version"
  end
end
