# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outfitpicker < Formula
  desc "Terminal app for choosing outfits from a local wardrobe directory."
  homepage "https://github.com/dh85/outfitpicker"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dh85/outfitpicker/releases/download/v0.1.0/outfitpicker_0.1.0_darwin_amd64.tar.gz"
      sha256 "5b70e493134492c178d2f42a6f94f270114ab1d1e306d16e638960f638c3ad78"

      define_method(:install) do
        bin.install "outfitpicker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dh85/outfitpicker/releases/download/v0.1.0/outfitpicker_0.1.0_darwin_arm64.tar.gz"
      sha256 "a778c70e73b8915b020dd4076cd0621d6cc5075776fe4c4f71e13aefcfc0a466"

      define_method(:install) do
        bin.install "outfitpicker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dh85/outfitpicker/releases/download/v0.1.0/outfitpicker_0.1.0_linux_amd64.tar.gz"
      sha256 "2318466ff589a589caee8c8fc09aa47d6e2607b592dafd8be5b0b8b3b62738b5"
      define_method(:install) do
        bin.install "outfitpicker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dh85/outfitpicker/releases/download/v0.1.0/outfitpicker_0.1.0_linux_arm64.tar.gz"
      sha256 "f2aef598684eb974ee2db211d87cee844e23e271d952c80812576def00387993"
      define_method(:install) do
        bin.install "outfitpicker"
      end
    end
  end

  test do
    system "#{bin}/outfitpicker", "--version"
  end
end
