# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outfitpicker < Formula
  desc "Interactive CLI to pick outfits from category folders"
  homepage "https://github.com/dh85/outfitpicker"
  version "1.0.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dh85/outfitpicker/releases/download/v1.0.3/outfitpicker_Darwin_x86_64.tar.gz"
      sha256 "36fad731f005d16584762136fc9ff5e5bd9fbe55649b5b87730dc92257789c28"

      def install
        bin.install "outfitpicker"
        bin.install "outfitpicker-admin"
      end
    end
    on_arm do
      url "https://github.com/dh85/outfitpicker/releases/download/v1.0.3/outfitpicker_Darwin_arm64.tar.gz"
      sha256 "200d9553cd5018a9eda06071210c9ed1203370cce89d195b0464d53420b9db38"

      def install
        bin.install "outfitpicker"
        bin.install "outfitpicker-admin"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dh85/outfitpicker/releases/download/v1.0.3/outfitpicker_Linux_x86_64.tar.gz"
        sha256 "589c8b2fc83f8732cedfc2654a70de7c5837f0f041365bc8ffc0865b831898b9"

        def install
          bin.install "outfitpicker"
          bin.install "outfitpicker-admin"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dh85/outfitpicker/releases/download/v1.0.3/outfitpicker_Linux_arm64.tar.gz"
        sha256 "f9808a43f9fe5741958779fca361b30341e228fb43dfa1d6ee68abc9d54cd1ea"

        def install
          bin.install "outfitpicker"
          bin.install "outfitpicker-admin"
        end
      end
    end
  end

  test do
    system "#{bin}/outfitpicker", "--version"
  end
end
