# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpotifyPlaylist < Formula
  desc "CLI tool to display formatted Spotify playlists."
  homepage "https://github.com/dh85/spotify-playlist"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dh85/spotify-playlist/releases/download/v0.5.0/spotify-playlist_0.5.0_darwin_amd64.tar.gz"
      sha256 "c4f5c649b868ad2c2e615c9666b64211a254dd34cb248a386a481bbe0337c39e"

      define_method(:install) do
        bin.install "spotify-playlist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dh85/spotify-playlist/releases/download/v0.5.0/spotify-playlist_0.5.0_darwin_arm64.tar.gz"
      sha256 "b1fbb8b59de5df05197663dc5bb858980c23bddf1454f48e729936585a6bd050"

      define_method(:install) do
        bin.install "spotify-playlist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dh85/spotify-playlist/releases/download/v0.5.0/spotify-playlist_0.5.0_linux_amd64.tar.gz"
      sha256 "7f561315911303142ded5e52ffc84ac417325fdbc15f7ac6e7fd8163a1eb58bc"
      define_method(:install) do
        bin.install "spotify-playlist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dh85/spotify-playlist/releases/download/v0.5.0/spotify-playlist_0.5.0_linux_arm64.tar.gz"
      sha256 "f5d08b2b70c2f29e5add6cd5d565534402b696f2ec20431a7010b4aa9f250ae1"
      define_method(:install) do
        bin.install "spotify-playlist"
      end
    end
  end

  test do
    system "#{bin}/spotify-playlist", "--version"
  end
end
