# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SpotifyPlaylist < Formula
  desc "CLI tool to display formatted Spotify playlists."
  homepage "https://github.com/dh85/spotify-playlist"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dh85/spotify-playlist/releases/download/v0.3.0/spotify-playlist_0.3.0_darwin_amd64.tar.gz"
      sha256 "150d01815b28b036ace9cc3a0a380273a8a3ead7a73d2d612656dbef50d6aea4"

      define_method(:install) do
        bin.install "spotify-playlist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dh85/spotify-playlist/releases/download/v0.3.0/spotify-playlist_0.3.0_darwin_arm64.tar.gz"
      sha256 "4cbfe04cbb24a46c5164cb82765bb404b4934600c75217e8db7cdde34e99c4f1"

      define_method(:install) do
        bin.install "spotify-playlist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dh85/spotify-playlist/releases/download/v0.3.0/spotify-playlist_0.3.0_linux_amd64.tar.gz"
      sha256 "d2f93a404999618969f7002a4e0e1918831350590807a2b2c10db0f1c7f3b40b"
      define_method(:install) do
        bin.install "spotify-playlist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dh85/spotify-playlist/releases/download/v0.3.0/spotify-playlist_0.3.0_linux_arm64.tar.gz"
      sha256 "ca8ec268b6c45b41fc8db50b04bbecdaa751a22c66fa408c32e3e5e04aa68600"
      define_method(:install) do
        bin.install "spotify-playlist"
      end
    end
  end

  test do
    system "#{bin}/spotify-playlist", "--version"
  end
end
